name: Deploy Brava POS

on:
  push:
    branches:
      - V2-Estable-Cloud

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd BravaPos-Comercial
            sudo docker compose exec -T db pg_dump -U bravapos_user bravapos_db > pre_deploy.sql
            
            if ! (git pull origin V2-Estable-Cloud && \
                  sudo docker compose up -d --build && \
                  sudo docker compose exec -T backend python manage.py migrate); then
              
              echo "⚠️ Error detectado. Iniciando Rollback de Base de Datos..."
              
              cat pre_deploy.sql | sudo docker compose exec -T db psql -U bravapos_user bravapos_db
              
              echo "✅ Rollback completado. El sistema volvió al estado anterior."
              exit 1
            fi
            
            echo "🚀 Brava POS actualizado con éxito."